language: node_js
git:
  depth: 3
notifications:
  email: false
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - "cd packages/core"
  - "yarn prod"
  - "yarn test:ci"
after_success:
  - "yarn nyc report --reporter=text-lcov | coveralls"
