language: node_js
git:
  depth: 3
notifications:
  email: false
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - "scripts/test.sh"
after_success:
  - "scripts/report-coverage.sh"
  - "scripts/compile-demo.sh"
