language: node_js
git:
  depth: 3
notifications:
  email: false
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - "scripts/test.sh"
  - "scripts/compile-demo.sh"
after_success:
  - "scripts/report-coverage.sh"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: packages/demo/dist
  on:
    branch: master
