language: node_js
git:
  depth: 3
notifications:
  email: false
node_js:
  - "8"
  - "9"
cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - "cd packages/core"
  - "npm run prod"
  - "npm run test:ci"
after_success:
  - "cd packages/core && ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls"
